src/biogps/apps/plugin/urls.py
from django.conf.urls import url

from .views import PluginViewSet


plugin_library = PluginViewSet.as_view({
    "get": "plugin_library",
    "post": "add_plugin"
})
plugin_view = PluginViewSet.as_view({
    "get": "get_plugin",
    "put": "update_plugin",
    "delete": "delete_plugin"
})
pluginlist = PluginViewSet.as_view({
    "get": "plugin_list"
})
plugin_url_test = PluginViewSet.as_view({
    "get": "test_plugin_url"
})
plugin_renderurl = PluginViewSet.as_view({
    "get": "render_url"
})
plugin_flag = PluginViewSet.as_view({
    "get": "flag"
})


urlpatterns = [
    url(r'^$', plugin_library),
    url(r'^(?P<plugin_id>\d+)(?:/(?P<slug>[\w-]*))?/$', plugin_view),
    url(r'^list/$', pluginlist),
    url(r'^all/$', pluginlist),
    url(r'^tag/$', pluginlist),

    # /species/human/
    # /tag/expression/
    # /species/human/tag/expression/
    # /tag/expression/species/human/
    url(r'^species/(?P<species>[\w-]+)(?:/tag/(?P<tag>[\w-]+))?/$',
        pluginlist),
    url(r'^tag/(?P<tag>[\w-]+)(?:/species/(?P<species>[\w-]+))?/$',
        pluginlist),

    # This gets used to generate the URLs for tags in plugin list views
    url(r'^tag/(?P<tag>[\w\s-]+)/$',
        pluginlist,
        name='plugin_list_for_tag'),

    url(r'test/$', plugin_url_test, name='test_plugin_url'),
    url(r'^(?P<plugin_id>\d+)/renderurl/$', plugin_renderurl),
    url(r'^(?P<plugin_id>\d+)/flag/$', plugin_flag),
]

src/biogps/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.models import User

from rest_framework import routers, serializers, viewsets

from biogps.apps.auth2 import views as auth2_views

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^api/gene/', include('biogps.apps.gene.urls')),
    url(r'^api/plugin/', include('biogps.apps.plugin.urls')),
    url(r'^api/layout/', include('biogps.apps.layout.urls')),
    url(r'^api/genelist/', include('biogps.apps.genelist.urls')),


    url(r'^auth/', include('biogps.apps.auth2.urls')),  # this is through https
    url(r'^authx/', include('biogps.apps.auth2.urls_x')),

    url('^accounts/orcid/login/$',
        auth2_views.biogps_oauth2_login,
        name='orcid_login'),
    url('^accounts/orcid/login/callback/$',
        auth2_views.biogps_oauth2_callback,
        name='orcid_callback'),

    url('^accounts/social/signup/$',
        auth2_views.social_signup,
        name='socialaccount_signup'),
    url(r'^accounts/', include('allauth.urls')),
    #url(r'^account/', include('django_authopenid.urls')),
    url(r'^profile/', include('biogps.apps.bgprofile.urls')),

]

src/biogps/apps/plugin/models.py
'''Models definition for BioGPS plugins.'''

import re
from django.db import models
from django_extensions.db.fields import AutoSlugField
from django.template.defaultfilters import slugify
from django.contrib.sites.models import Site

from tagging.registry import register

from biogps.apps.auth2.models import UserProfile
from biogps.utils.models import BioGPSModel, Species
from biogps.utils.fields.jsonfield import JSONField
from biogps.apps.search.build_index import set_on_the_fly_indexing

from biogps.apps.plugin.fields import SpeciesField


class BiogpsPlugin(BioGPSModel):
    '''Model definition for BioGPSPlugin.'''
    title = models.CharField(max_length=100)
    url = models.CharField(max_length=500)
    ownerprofile = models.ForeignKey(UserProfile, to_field='sid',
                                     db_column='authorid')
    author = models.CharField(max_length=100)
    type = models.CharField(max_length=20)
    options = JSONField(blank=True, editable=False)
    description = models.TextField(blank=True)
    short_description = models.CharField(blank=True, max_length=140)
    lastmodified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    slug = AutoSlugField(populate_from='title')
    species = SpeciesField(max_length=1000)

    #required setting for ModelWithPermission and PermissionManager working
    object_type = 'P'
    #short_name will be used as the index_type for ES indexing
    short_name = 'plugin'

    class Meta:
        permissions = (
            ("can_share_plugin", "Can share plugins with others."),
        )
        ordering = ("title",)
        get_latest_by = 'lastmodified'

    def __unicode__(self):
        return u'"%s" by "%s"' % (self.title, self.author)

    @models.permalink
    def get_absolute_url(self):
        """ Returns the appropriate URL for this plugin. """
        _slug = slugify(self.title)
        if _slug:
            return ('plugin_show', [str(self.id), _slug])
        else:
            return ('plugin_show', [str(self.id), ])

    def object_cvt(self, mode='ajax'):
        '''A helper function to convert a BiogpsPlugin object to a simplified
            python dictionary, with all values in python's primary types only.
            Such a dictionary can be passed directly to fulltext indexer or
            serializer for ajax return.

          @param mode: can be one of ['ajax', 'es'], used to return slightly
                         different dictionary for each purpose.
          @return: an python dictionary
        '''
        extra_attrs = {'name': 'title',
                       'AS_IS': ['description', 'short_description',
                                 'species', 'type', 'url', 'shortUrl',
                                 'usage_data', 'options']}
        out = self._object_cvt(extra_attrs=extra_attrs, mode=mode)
        out['popularity'] = self.popularity.score
        return out

    #==========================================================================
    # methods specific for this model
    #==========================================================================
    @property
    def shortUrl(self):
        '''Extracts only the domain from a URL.  Used when displaying the
          'small' plugin template.  It works by doing 2 RegEx substitutions to:
               1. Strip out everything up to and including ://
               2. Strip out everything after and including the next /
        '''
        p = re.compile('.*\:\/\/')
        p2 = re.compile('\/.*')
        url = p2.sub('', p.sub('', self.url))
        return 'biogps.org' if url == '' else url

    def permissionClass(self):
        perm = self.get_role_permission(returnsorted=True,
                                        returnshortname=True)
        return perm[0] if perm else 'myself'

    def uses_all_species(self):
        '''Confirm whether this plugin is available for all species or not.
           Returns True when the instance's species field is either None or
           matches the full list of available species. Returns False when one
           or more of the available species are not in the instance's list.
        '''
        if self.species:
            for s in Species.available_species:
                if s not in self.species:
                    return False
        return True

    @property
    def usage_data(self):
        stats = {}
        stats['users'] = self.popularity.users_count
        stats['layouts'] = self.popularity.score
        return stats

    @property
    def usage(self):
        '''return the list of layouts using this plugin.'''
        return self.biogpsgenereportlayout_set.all()

    def usage_count(self, user):
        '''Return a tuple for (cnt_mylayouts, cnt_otherslayouts).'''
        used_layouts = self.biogpsgenereportlayout_set.all()
        cnt_total = used_layouts.count()
        if cnt_total > 0:
            cnt_mylayouts = (user.mylayouts.all() & used_layouts).count()
        else:
            cnt_mylayouts = 0
        return (cnt_mylayouts, cnt_total - cnt_mylayouts)

    def usage_users(self):
        '''Return number of unique users using plugin'''
        unique_users = list()
        layouts = self.biogpsgenereportlayout_set.all()
        for i in layouts:
            if i.author not in unique_users and \
               i.author.lower().find('demo') == -1:
                unique_users.append(i.author)

        return len(unique_users)

    def usage_percent(self):
        '''Return the percentage of total layouts that use this plugin.'''
        from biogps.layout.models import BiogpsGenereportLayout
        stats = {
            'layouts': self.biogpsgenereportlayout_set.count() * 100.0 / BiogpsGenereportLayout.objects.count()
        }
        return stats

    def getKeywords(self, url=None):
        url = url or self.url
        if url:
            kwd_list = re.findall('(\{\{[\s\w|:.]+\}\})', url)
            return kwd_list
        else:
            return []

    def geturl(self, gene, mobile=False):
        '''rendering actual url given input gene
           gene is a object returned by DataService.GetGeneIdentifiers
           if mobile is true, using alt. mobile_url if provided.
        '''
        return _plugin_geturl(self, gene, mobile=mobile)

    def update_options(self, **kwargs):
        _options = self.options or {}
        _options.update(kwargs)
        if _options:
            self.options = _options
            self.save()

    def add_mobile_url(self, murl):
        '''Add optional "mobile_url" field in plugin.options to specify
           alternative url template for mobile page.
        '''
        self.update_options(mobile_url=murl)

    @property
    def allowedspecies(self):
        return self.species

    @property
    def mobile_url(self):
        return self.options['mobile_url'] if 'mobile_url' in self.options else None

    @property
    def certified_owner(self):
        return self.options and 'certified_owner' in self.options and self.options['certified_owner']

    def flag_as_certified_owner(self):
        '''Add optional "certified_owner" flag to indicate this plugin's owner
           is certified.
        '''
        self.update_options(certified_owner=True)


def init_handler(sender, **kwargs):
    '''Handle post-initialization for model.
       Initialize species field when backwards compatibility is needed.
       Populates short_description with the beginning of description if not defined.
    '''
    instance = kwargs['instance']
    # Handle the species
    if instance.uses_all_species():
        # Additional check for backwards-compatibility
        if instance.options and 'allowedSpecies' in instance.options:
            instance.species = instance.options['allowedSpecies']

    # Handle the short_description
    if not instance.short_description:
        if instance.description:
            import textwrap
            max_length = 140
            if len(instance.description) > max_length:
                instance.short_description = textwrap.wrap(instance.description, max_length-3)[0] + '...'
            else:
                instance.short_description = instance.description
        else:
            instance.short_description = "No summary provided."

models.signals.post_init.connect(init_handler, BiogpsPlugin,
                                 dispatch_uid='BiogpsPlugin_init_handler')

def create_handler(sender, **kwargs):
    '''Handle post-creation for Plugin model.
       Creates a Popularity object for the given instance.
    '''
    if kwargs['created']:
        #create an entry on popularity table
        BiogpsPluginPopularity.objects.create(plugin=kwargs['instance'], score=0)

models.signals.post_save.connect(create_handler, BiogpsPlugin,
                                 dispatch_uid='BiogpsPlugin_create_handler')

register(BiogpsPlugin)
set_on_the_fly_indexing(BiogpsPlugin)


class PluginUrlRenderError(Exception):
    pass


def _get_value(kwd, gene,
               idx_filter_separator='.',       # e.g., {{MGI.1}}
               value_field_separator=':',      # e.g., "MGI:104772"
               list_separator=','):            # if matching values are a list
    k = kwd.strip().lower()
    _idx_filter = None
    if len(k.split(idx_filter_separator)) == 2:
        #support for something like "{{MGI:2}}"
        #will take only "104772" part of "MGI:104772" value
        k, _idx_filter = k.split(idx_filter_separator)
        try:
            _idx_filter = int(_idx_filter)     # _idx_filter starts from 0
        except ValueError:
            return None

    value = gene.get(k, None)
    if value:
        if isinstance(value, (list, tuple)):

src/biogps/apps/plugin/forms.py
import types
from django import forms

from biogps.utils.models import Species
from models import BiogpsPlugin
from fields import SpeciesSelectMultiple

class BiogpsPluginForm(forms.ModelForm):
    species = forms.MultipleChoiceField(
                    choices=Species.form_choices(),
                    widget=SpeciesSelectMultiple(),
                    initial=Species.available_species,
                    required=False
              )

    class Meta:
        model = BiogpsPlugin
        fields = ('title', 'url', 'description', 'short_description', 'species')

    def __init__(self, *args, **kwargs):
        # Ensure we get the full species list.
        # Effectively all we're doing is copying 'species[]' to 'species' to
        # deal with the difference between Django and jQuery's representations
        # of arrays passed through URLs.
        if args:
            _dict = args[0].copy()      # Create a mutable copy of the QueryDict
            _dict.setlist('species', _dict.getlist('species[]'))
            _args = (_dict,)            # Create a new args tuple to pass on as normal
        else:
            _args = args
        super(BiogpsPluginForm, self).__init__(*_args, **kwargs)

src/biogps/apps/plugin/templates/_form.html
<form action="{% if plugin %}{{ plugin.get_absolute_url }}
    {% else %}{% url 'plugin_home' %}{% endif %}" method="post">
<div class="object-summary
            {% if plugin.is_restricted %}object-restricted{% endif %}
            {% if plugin.is_private %}object-private{% endif %}">
    {% if plugin %}
    <h1>Edit Your Plugin: {{ plugin.title }}</h1>
    <input id="id_id" type="hidden" name="id" value="{{ plugin.id }}">
    {% else %}
    <h1>Register a New Plugin</h1>
    {% endif %}

    <div class="fieldWrapper">
        <label for="id_title" class="fieldName"><b>Title:</b></label><br>
        {{ form.title }}
    </div>

    <div class="fieldWrapper">
        <label for="id_url" class="fieldName"><b>URL Template:</b></label><br>
        <input id="id_url" type="text" name="url" value="{{ plugin.url }}" maxlength="500"
            data-complete='[
                { "label": "Entrez GeneID", "value": "entrezgene", "category": "" },
                { "label": "Symbol", "value": "symbol", "category": "" },
                { "label": "Ensembl GeneID", "value": "ensemblgene", "category": "" },
                { "label": "UniGene ID", "value": "unigene", "category": "" },
                { "label": "Uniprot ID", "value": "uniprot", "category": "" },
                { "label": "RefSeq Transcript", "value": "refseqmrna", "category": "" },
                { "label": "RefSeq Protein", "value": "refseqprotein", "category": "" },
                { "label": "Ensembl Transcript", "value": "ensembltranscript", "category": "" },
                { "label": "Ensembl Protein", "value": "ensemblprotein", "category": "" },
                { "label": "PDB ID", "value": "pdb", "category": "" },

                { "label": "Genome Assembly", "value": "assembly", "category": "More Options" },
                { "label": "Genomic Location", "value": "genomelocation", "category": "More Options" },
                { "label": "Chromosome", "value": "chr", "category": "More Options" },
                { "label": "Genomic Start Position", "value": "gstart", "category": "More Options" },
                { "label": "Genomic End Position", "value": "gend", "category": "More Options" },
                { "label": "Alias", "value": "alias", "category": "More Options" },

                { "label": "FLYBASE", "value": "FLYBASE", "species": "fruitfly", "category": "Species-Specific" },
                { "label": "HGNC", "value": "HGNC", "species": "human", "category": "Species-Specific" },
                { "label": "HPRD", "value": "HPRD", "species": "human", "category": "Species-Specific" },
                { "label": "PharmGKB", "value": "PharmGKB", "species": "human", "category": "Species-Specific" },
                { "label": "MGI", "value": "MGI", "species": "mouse", "category": "Species-Specific" },
                { "label": "OMIM", "value": "MIM", "species": "human", "category": "Species-Specific" },
                { "label": "RATMAP", "value": "RATMAP", "species": "rat", "category": "Species-Specific" },
                { "label": "RGD", "value": "RGD", "species": "rat", "category": "Species-Specific" },
                { "label": "TAIR", "value": "TAIR", "species": "thale-cress", "category": "Species-Specific" },
                { "label": "WormBase", "value": "WormBase", "species": "nematode", "category": "Species-Specific" },
                { "label": "Xenbase", "value": "Xenbase", "species": "frog", "category": "Species-Specific" },
                { "label": "ZFIN", "value": "ZFIN", "species": "zebrafish", "category": "Species-Specific" }

            ]'>
        <a id="btn-test_url" class="requires-js" href="#">Test</a>
        <div id="result-test_url"></div>
    </div>

    <div class="fieldWrapper">
        <label for="id_short_description" class="fieldName"><b>Summary:</b> Describe this plugin in one tweet (140 characters or less)</label><br>
        {{ form.short_description }}
        <span id="id_short_description_count" class="charCounter"></span>
    </div>

    <div class="fieldWrapper">
        <span class="fieldName"><b>Sharing Permissions:</b> who else on BioGPS gets to use this plugin?</span>
        <div id="id_rolepermission">
            <input id="id_rolepermission0" type="radio" name="rolepermission" value="biogpsusers"
                {% if not plugin or plugin.is_public %}checked="checked"{% endif %}>
            <label for="id_rolepermission0">Public</label>

            {% if user.is_gnf_user or user.is_nvs_user %}
            <input id="id_rolepermission1" type="radio" name="rolepermission" value="novartisusers">
            <label for="id_rolepermission1">GNF &amp; Novartis</label>
            {% endif %}

            <input id="id_rolepermission2" type="radio" name="rolepermission" value="friendusers">
            <label for="id_rolepermission2">Only My Friends</label>

            <input id="id_rolepermission3" type="radio" name="rolepermission" value="myself"
                {% if plugin.is_private %}checked="checked"{% endif %}>
            <label for="id_rolepermission3">Not Shared</label>
        </div>
    </div>
</div>

<div class="object-full-details">
    <div class="fieldWrapper">
        <span class="fieldName"><b>Species:</b> Select which species this plugin supports.</span>
        {{ form.species }}
    </div>

    <div class="fieldWrapper">
        <label for="id_tags" class="fieldName"><b>Tags:</b> (categories)<br>
            <span class="extra-details">Separate each tag by a space. For multi-word tags, use dashes (e.g. "text-mining").</span>
        </label><br>
        <input id="id_tags" type="text" name="tags" value="{{ plugin.tags|join:" " }}" maxlength="500"
            data-complete='[
            {% for t in all_tags %}
                "{{ t|addslashes }}"{% if not forloop.last %},{% endif %}
            {% endfor %}
            ]'>
    </div>

    <div class="fieldWrapper">
        <label for="id_description" class="fieldName"><b>Full Description:</b></label><br>
        {{ form.description }}
    </div>


    <div class="form-controls">
        <input type="submit" value="{% if plugin %}Save Changes{% else %}Register Plugin{% endif %}" class="btn-use-object btn-priority-primary btn-large">
        <a href="{% if plugin %}{{ plugin.get_absolute_url }}
            {% else %}{% url 'plugin_home' %}{% endif %}" class="btn-use-object">Cancel</a>
    </div>
</div>
</form>

src/biogps/apps/plugin/templates/_form_help.html
<h2>URL Template Syntax</h2>
<p>You need to supply the URL to the website you want to add
as a plugin, including one (or more) keywords. When you then
use your plugin in a layout, the appropriate identifier for
your gene of interest will be substituted in.</p>
<p>For example, to make a simple Google search plugin, you would
type in the URL below, then click
the "Add Keyword" button and select whichever identifier you want.<br>
<b>http://www.google.com/search?q=</b></p>
<p>Once you have picked an identifier, the URL template
will then look like this:<br>
<b>http://www.google.com/search?q=&#123;&#123;Symbol&#125;&#125;</b></p>
<p>When the plugin is then used in a layout to look at a gene,
BioGPS will automatically insert the correct value. For
example, if you used the UniGene ID keyword and the user
is looking at CDK2, the actual URL that will load would be
this:<br>
<b>http://www.google.com/search?q=Hs.19192</b></p>
<p>If you want to test your URL template before saving, just hit
the "Test" button at the bottom of this page.
</p>

src/biogps/apps/plugin/templates/edit.html
{% extends "NEW/base_site.html" %}

{% block title %}Edit {{ plugin.title }} Plugin{% endblock %}
{% block bodyclass %}plugin{% endblock %}

{% block content %}
<article id="plugin-form">
    <div class="in">
        {% include "_form.html" %}
    </div>
</article>

<aside id="sidebar-right">
    <div class="in">
        {% include "_form_help.html" %}
    </div>
</aside>
{% endblock %}

src/biogps/apps/plugin/templates/index.html
{% extends "NEW/base_site.html" %}

{% block title %}Plugin Library{% endblock %}
{% block bodyclass %}{% endblock %}

{% block content %}
<article class="shift-for-sidebar-left">
    <div class="in">
        <header id="page-header">
            <h1 id="page-header-text">{{ navigation.title }}</h1>
            <div id="page-alt-nav">
                <a href="/plugin/new/" class="jq-button ui-priority-primary">Create a Plugin</a>
            </div>
        </header>
        <p class="large-summary"><b>Plugins are 3rd party websites that you can
            use to learn more about your gene of interest.</b> BioGPS makes it
            easy and quick to use your favorite gene-centric databases. Plugins
            are the backbone of BioGPS and can be combined into custom
            Layouts for viewing many at once.
            <a href="/help_steps/">Learn more</a>.</p>

        <div class="browse-tabs jq-tabs">
            <ul>
                {% for l in list1 %}
                <li><a href="#tabs-{{ forloop.counter }}">{{ l.name }}</a></li>
                {% endfor %}
            </ul>
            {% for l in list1 %}
                <div id="tabs-{{ forloop.counter }}" class="browse-tab-list">
                    <ul>
                    {% for p in l.items %}
                        <li><a href="{{ p.get_absolute_url }}"
                            {% if p.short_description %}
                                class="has-tooltip" title="{{ p.short_description }}"
                            {% endif %}>{{ p.title }}</a></li>
                    {% endfor %}
                    {% if l.more %}
                        <li><a class="more-link" href="{{ l.more }}">more &rsaquo;</a></li>
                    {% endif %}
                    </ul>
                </div>
            {% endfor %}
        </div>

        <section>
            {% for l in list2 %}
                <div class="browse-category-highlights">
                    <h2><a href="{{ l.more }}">{{ l.name }}</a></h2>
                    <ul>
                    {% for p in l.items %}
                        <li><a href="{{ p.get_absolute_url }}"
                            {% if p.short_description %}
                                class="has-tooltip" title="{{ p.short_description }}"
                            {% endif %}>{{ p.title }}</a></li>
                    {% endfor %}
                        <li><a class="more-link" href="{{ l.more }}">more &rsaquo;</a></li>
                    </ul>
                </div>
            {% endfor %}
        </section>

        <nav id="browse-footer-nav" style="display:none">
            <div>
                <a href="/plugin/all/" class="jq-button">List all Plugins</a>
            </div>
            <div>
                <a href="/plugin/tag/" class="jq-button">Show all Categories</a>
            </div>
            <div>
                <a href="/plugin/new/" class="jq-button">Suggest a Plugin</a>
            </div>
        </nav>
    </div>
</article>

<aside id="sidebar-left" class="browse-navigation">
    <div class="in">
        {% include "search/navigation.html" %}
    </div>
</aside>
{% endblock %}

src/biogps/apps/plugin/templates/new.html
{% extends "NEW/base_site.html" %}

{% block title %}New Plugin{% endblock %}
{% block bodyclass %}plugin{% endblock %}

{% block content %}
<article id="plugin-form">
    <div class="in">
        {% include "_form.html" %}
    </div>
</article>

<aside id="sidebar-right">
    <div class="in">
        {% include "_form_help.html" %}
    </div>
</aside>
{% endblock %}

src/biogps/apps/plugin/templates/newplugin_notification.html
<html>
<body>
	<h2>New plugin added.</h2>
	<table border="1" style="margin: 10px 20px 10px 20px; border-collapse: collapse; padding-left: 5px; padding-right: 5px;">
		<tr><td><b>id</b></td><td>{{p.id}}</td></tr>
		<tr><td><b>title</b></td><td>{{p.title}}</td></tr>
		<tr><td><b>Url template</b></td><td>
		         {{p.url}}
		         <p>Sample Links:&nbsp;
		            <a href="http://{{site}}/plugin_v1/{{p.id}}/renderurl/?geneid=1017&redirect">CDK2</a>&nbsp;&nbsp;
		            <a href="http://{{site}}/plugin_v1/{{p.id}}/renderurl/?geneid=695&redirect">BTK</a>&nbsp;&nbsp;
		            <a href="http://{{site}}/plugin_v1/{{p.id}}/renderurl/?geneid=7157&redirect">TP53</a>&nbsp;&nbsp;
		         </p>
		        </td></tr>
		<tr><td><b>author</b></td><td>{{p.author}}</td></tr>
		<tr><td><b>tags</b></td><td>
                                {% for tag in p.tags %}
                                {{tag.name}}{%if not forloop.last %},{% endif %}
                                {% endfor %}
                                </td></tr>
		<tr><td><b>permission</b></td><td>{{p.permission}}</td></tr>
		<tr><td><b>summary</b></td><td>{{p.short_description}}</td></tr>
		<tr><td><b>description</b></td><td>{{p.description}}</td></tr>
		<tr><td><b>species</b></td><td>{{p.species}}</td></tr>
		<tr><td><b>options</b></td><td>{{p.options}}</td></tr>
        <tr><td></td><td>
                     <a href="https://{{site}}/siteadmin/www/biogpsplugin/{{p.id}}/">View this plugin on admin interface</a><br />
                     <a href="http://{{site}}{{p.get_absolute_url}}">View this plugin in Plugin library</a>  (if you have the permission)
                     </td></tr>
	</table>
</body>
</html>

src/biogps/apps/plugin/templates/tags.html
{% extends "NEW/base_site.html" %}

{% block title %}Plugin Tags{% endblock %}
{% block bodyclass %}{% endblock %}

{% block content %}
<article class="shift-for-sidebar-left">
    <div class="in">
        <header id="page-header">
            <h1 id="page-header-text">Plugin Tags</h1>
        </header>
        <p class="large-summary"><b>A tag is a keyword or label that
            categorizes plugins with other, similar plugins.</b> Using the
            right tags makes it easier for others to find and use your plugin.
        </p>

        <p><b>Sort by: </b><a href="/plugin/tag/">Name</a> | <a href="/plugin/tag/?sort=popular">Popularity</a></p>

        <section id="tag-list">
            <ul>
            {% for t in all_tags %}
                <li>
                    <a href="{% url 'plugin_list_for_tag' t.name %}" rel="tag">
                        <span class="ui-icon ui-icon-tag2"></span>
                        {{ t }}
                        {% if t.count %}
                        <span class="count">({{ t.count }})</span>
                        {% endif %}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </section>
    </div>
</article>

<aside id="sidebar-left" class="browse-navigation">
    <div class="in">
        {% include "search/navigation.html" %}
    </div>
</aside>
{% endblock %}